---
title: "Nigeria data report"
author: "Tomas Morley"
date: "10 December 2016"
output: word_document
---

The data for this report come from the nationally representative 2010-11 and 2012-13 waves of the  Nigeria General Household Survey (GHS). In total the GHS is a cross section of 22,000 households, 5,000 of which were included as panel households forming the GHS-panel. A relatively low rate of attrition was recorded between the two waves amounting to a 96% successful follow up rate across all households and 97% among only rural households. The focus of the GHS is to improve the quality of data on the agricultural sector and was conducted by the National Bureau of Statistics in partnership with the Federal Ministry of Agriculture and Rural Development (FMA&RD), the National Food Reserve Agency (NFRA), the Bill and Melinda Gates Foundation (BMGF) and the World Bank (WB). In each wave, households were visited twice reflecting the post planting and post harvest visits. In addition to agricultural activities, a broad range of topics including agricultural production, consumption, health and a number of socio-economic characteristics were recorded. The data was collected at several levels, including at the plot, household and enumeration area level, and the location of each household was GPS recorded with an offset to preserve household anonymity.

We approach the study of smallholder maize productivity from the perspective of narrowing the yield gap by identifying the role of nitrogen application rates on maize yields. The agricultural questionnaire of the GHS records key information at the plot level including the quantity of maize harvested, the quantity of fertilizer applied and the area of the plot. From this information maize yield, and nitrogen application rates can be calculated. Plot area measurements were recorded by GPS in each wave, and where it was not possible to record the GPS area, for example due to cloudy weather, the World Bank provides a complete set of plot areas with imputed missing values. Another aspect of this study is the extent to which nitrogen application rates reflect economically meaningful decisions. This is informed by the relative price of maize and nitrogen, both of which can be derived from the GHS survey. As some price measurements clearly fell outwith an acceptable or plausible range, the prices of both maize and nitrogen were winsored to remove values that were more than three standard deviations from the median (probably should be done per region??). A subsidy program did exist in Nigeria over the course of this survey. However, farmers were not asked whether they received these subsidies for the fertilizer they purchased which may also have consequences for the analysis ... 

Maize yields may also depend on factors including the amount of labour on a plot, or farmer characteristics. In addition the biophysical role of nitrogen on maize can also depend on soil, seed type  and climate conditions, for example the carbon content of the soil (Barrett). To some extent this information is included in the GHS and the spatial and climate data that accompanies the main survey. In this report we go further by using the GPS recorded household locations to combine the GHS with external data with a finer resolution than currently provided with the GHS survey. We therefore have more accurate information on key variables to improve the analysis of the maize yield gap and the role of nitrogen application.    
