---
title: "Yield gap estimation at the farm level: Extensions, measurement issues and application"
author: "Michiel van Dijk"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  word_document:
    reference_docx: ../Common//word_styles_01.docx
bibliography: ../common/YGDEF.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction
Yield gap is a powerful concept to illustrate by how much crop yield can be increased.  and has therefore been used by both policy makers.  Despite its abundant use, various definitions are used to measure the yield gap which are not always comparable [@Sumberg]. 

In a recent paper, @Fischer2015 reviewed the various definitions of yield levels and yield gaps. This work expands the work of Fisher and builds on Van Dijk et al. [@Van Dijk] and Silva et al. [@Silva] by contrasting and extending agricultural/agronomical(?) definitions of crop yield and yield gap with comparable but conceptually different measures used in the economic literature. A well-known observation in the yield gap literature is that yields tend to stagnate at around 70-85 percent of potential yield [@Cassman1999; @Cassman2003; @Lobell2009, @Vanittersum2013, @Fischer2015]. The common explanation for this phenomenon is that it is simply not economically viable for farmers to completely close the gap because of unfavourable input-output price combinations [@Fisher2014] or the additional costs that are associated with the 'fine-tuning' of crop management [@Cassman2003]. Empirical research on the exact size of this 'exploitable yield gap', which demand information on the prices of inputs and outputs is not common in the agronomic literature and the 75-85 percent gap is mainly based on 'general experience' [@Fischer2014]. This figure is commonly used in policy recommendations and assessments but not studies [van oort 2014, Aramburo 2015]. As Fischer points out "quote on costs and dev countries", this figure is likely to be a gross overstatement for developing counties characterised by large transport costs, etc.

Large differences between official crop yield statistics and independent yield surveys have been reported for African countries (see Van oort[2016 p. 3 for references, also include Gollin paper])

This paper aims to contributes to this knowlegde gap by emperically estimating 'economic yield level. Moreover, using a large nationally representative farm level survey on maize production in Nigeria, it provides and empirical study and comparison of the different yield levels and yield gaps, something which was missing in the theoretical paper of Fischer. It also illustrates the large impact of the impact of using diferent definitions of the two main components of yield: production and area, which is not explictely discussed by most yield gap studies.  

The structure of the paper is as follows. Section 2 provides a conceptual framework that integrates varies definitions of yield levels and yield gap. Section 3 briefly discusses the Nigerian farm level maize data set that is used to illustrate the conceptual model. Section 4 computes the yield levels and yield gaps followed by a discussion in Section 5. Finally, Section 6 concludes. 

# Conceptual framework
The literature on yield gaps identifies a number of yield levels that are used to estimate a variety of yield gaps. This section starts with summarizing several conventional yield levels, such as farm yield and potential yield [@Fischer, @Vanittersum] as well as a number of recent extentions that make it possible to decompose the yield gap in a number of components that explain the yield gap [@VanDijk, @Silva], followed by a describtion of various yield gaps and a discussion of measurement issues. 


_Potential yield._ Potential yield (PY) is defined as “the yield of a cultivar when grown in environments to which it is adapted, with nutrients and water non-limiting and with pests, diseases, weeds, lodging, and other stresses effectively controlled” [@Evans1999]. It depends on local climate factors, including  atmospheric CO2 emissions, solar radiation, temperature as well as plant characteristics [@vanIttersum1997]. _Water-limited potential yield_ 

_Actual yield._ Actual yield (Ya), also sometimes referred to as farm yield [@Fischer].

_maximum observed yield/._ This is the maximum observed yield in a sample of farmers or plots

_Attainable yield_ The notion of 'attainable' yield is used very frequently in the yield gap literature but in an inconsistent way, meaning a number of things. @Fischer2015 equates attainable yield with our definition of *economic yield* by defining it as *'the yield attained by a farmer from average natural resources when economically optimal practices and levels of inputs have been adopted while facing the vagaries of weather'* [p.32]. @Sadras use the following definition: *'the best yield achieved through skilful use of the best available technology'* [p. 6]. A similar definition is provided by [@Tittonell and Giller], who coin the term 'locally attainable yield'. In this case the concept of attainable yield to efficiency and use of best-available technology instead of economic constraints. We argue that this is the same to our definiton of *feasible yield*. Finally, several researchers take an emperical approach and estimate attainable yield as the average yield of plots or farms with the highest yield in the sample of observatons [@Hall, @Giller, @Laborte]. The criteria to select farmers is in most cases the top decile or 95% percentile of the cumulative relative frequency curve of yield estimates [@Hall]. In many cases, the emperically observed attainable yield is used as an approximation of (water-limited) potential yield. We argue that this definition of attainable yield is identical to the *best-farmers yield*. 

[LAborte 2012] uses best farmers yield CHECK.

Figure X demonstrates that the three definitions of attainable yield that are used in the literature refer to different farm decisions that are associated with different input-output combinations. Our stuydy on maize yield gaps in Nigeria also shows that the yield levels are far apart and therefore lead to different yield gap measures and, hence, conclusions on how to close the yield gap.   


_Technical efficiency yield_


_Exploitable yield._ 

_Economic yield._ This level is referred to as 'exploitable yield' by @Vanittersum2013. In the agronomic literature it is often assumed that the economic yield is 70-85% of potential yield. 

_Feasible yield._ Feasible yield represents the maximum feasible yield that can be reached on a plot with the available technology and best-practice management but without any economic constraints (e.g. inputs are free). This yield level is also sometimes referred to as ‘potential farm yield’ [@Datta1981], ‘maximum attainable yield’ [@FAO2004] and ‘technical on-farm ceiling yield’ [@DeBie2000]. 

Figure X combines agronomic literature on yield gap estimation and yield response functions with economic literature on technical efficiency and allocative efficiency with yield response function.
Figure X depicts the various levels into one diagram. It depicts input-output combinations of agricultural units (i.e. plots or farms). For the moment, we assume that the yield response function has only one output y (e.g. maize yield), one variable input x (e.g. nitrogen) and growth defining factors are the same for all observations.  All other inputs are fixed. 


## Yield gaps
The various yield levels can be combined to define a variety of yield levels. Table x summarizes the yield gaps that have been used in the literature [@Fischer, @VanDijk, @Silva, @van Ittersum], including a short describtion of what they intend to measure. The total yield gap (YG) is most commonly used in the agronomic literature and measures the potential to increase biophysical yield. In practice, farmers will often not reach this level for a variety of reseans that are captured by decompisitions of the total yield gap. not be able to reach the potential yield level because of econ 





## Measurement issues


Any yield level is defined as 

[FORMULA]

where x is crop production in tons (e.g. actual, economic or potential) and y is field size in ha. Several papers reviewed the measurment of actual yield and the impact of using different defintions [ADD].Crop production can be measured in three ways: (1)

Area can be measured in two ways. (1) Total plot size. (2) Harvested area. 

Althoughm most yield gap studies provide a definition of yield gap, there is hardly any discussion on the defintions of production and area. Production is... while the definition of area seems mostly to depend on the availabilyt of data. Global yield gap studies such as [@Fisher], [@Licker], [@Mueller] and [@Vanittersum] rely on FAOSTAT or national statistics data as input, which use the harvested area definition. Local scale studies mostly use small project-specific survey data that use the total plot size definition [@ADD]. data for  scale The GYGA uses data [Examples] [XXX] and As will be shown below, using field size or harvested area has a dramatic impact on yield and yield gap. 




at the beginning Although most yield gap papers provide a clear definition of the yield gap concept used 
- Measurement of yield: harvested area or plot size, measurement of production
- Confusion about attainable yield and economic yield 


# Important papers
- Lobell (2013) uses satelletite data and uses as benchmark maximum in sample
- Giller does the same and calls it attainable yield
- Joao's definition of resource yield gap
- Martin's papers on water-limited yield gap
- Fischer on definition of yield gaps
- Agronomic vs economic analyisis: copy of book that compares functional forms.
Reynolds et al. (2015) How Common Crop Yield Measures Misrepresent Productivity among Smallholder Farmers, ICAE.
Fermont and Benson (2011) Estimating Yield of Food Crops Grown by Smallholder Farmers: A Review in the Uganda Context, IFPRI Discussion Paper 01097

# Methods
## Data


## Estimation



# Maize yield levels and yield gaps in Nigeria
- calculate different yield gaps, also attainable yield gap and show differences
- Reflect on 20% rule

# Discussion


# Conclusions